Python to firebase crashlytics
endlessm/kolibri-installer-android pull request #91
Opened 2022-12-02 17:31 UTC by xcho1

2022-12-05 20:52 UTC, dylanmccall requested changes
A small commit history nitpick, but the final change set looks great!

2022-12-05 20:52 UTC, dylanmccall commented on src/java/org/learningequality/FullScreen.java
> -                }
Just to make things tidier, We should do a rebase so this change is in its own commit. Best thing might be to remove the change from this commit and instead add `git revert 150edf919d92b7cf953e895bdb645eaeb7bcd19e`.

2022-12-06 03:36 UTC, dylanmccall commented
Okay, I went ahead and did that rebasing! Need another reviewer, but I'm happy with the result now :)

2022-12-06 13:54 UTC, xcho1 commented
@dylanmccall, yeah it makes sense to split them into separate commits, thanks!

2022-12-09 00:53 UTC, dylanmccall commented
I gave this another look today and it's working for me, so I'll go ahead and merge it. Here's an example of a Python exception I was able to produce by abusing the `options.ini` file:

https://console.firebase.google.com/project/endless-key/crashlytics/app/android:org.endlessos.Key/issues/42f106d556a9a23ac402ae39064e4a3d?time=last-hour&sessionEventKey=639272D502B900011DB8235F4C39AC15_1753369069143524891

We might like to add more data to these crashes in the future as our needs evolve, but it seems pretty clear how to do that.

2022-12-09 00:53 UTC, merged

2022-12-12 14:39 UTC, manuq commented
Nice! The report is a bit hard to read but it is something!

2022-12-12 20:52 UTC, dylanmccall commented
> Nice! The report is a bit hard to read but it is something!

One thing that helps here is switching to plain text instead of formatted text in the stack trace viewer, so the line breaks work. Definitely a little crude, though.

2022-12-12 22:34 UTC, manuq commented
> > Nice! The report is a bit hard to read but it is something!
> 
> One thing that helps here is switching to plain text instead of formatted text in the stack trace viewer, so the line breaks work. Definitely a little crude, though.

Ah good advice thanks!